import Navbar from "@/components/Navbar";
import "./globals.css";
import { DotGothic16 } from "next/font/google";
import clsx from "clsx";
const dotGothic = DotGothic16({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          "text-black bg-white dark:text-white dark:bg-[#111010]",
          dotGothic.className,
          "max-w-7xl mx-auto"
        )}
      >
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
