import Navbar from "@/components/Navbar";
import "./globals.css";
import { DotGothic16 } from "next/font/google";
import clsx from "clsx";
const dotGothic16 = DotGothic16({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          "text-white bg-[#111010] font-extrabold tracking-widest",
          dotGothic16.className,
          "max-w-7xl mx-auto dark"
        )}
      >
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
