const About = () => {
  return (
    <div className="text-justify text-slate-200 font-bold text-lg">
      Experienced Software Developer with expertise in TypeScript, Node.js,
      Next.js, data structures, and algorithms. Known for efficient and scalable
      solutions. Proficient in API architecture and performance optimization.
      Passionate about innovative and maintainable code. Skilled in automation,
      including web scrapers. Seeking dynamic projects to drive business growth.
      <br />
      <br />
      <i>
        <small className="font-normal">
          Generated by Chat GPT because that&apos;s what it is good for or use
          it for an actual project and generate absolute garbage code
        </small>
      </i>
    </div>
  );
};

export default About;
